settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: service-analyzer-tiger
  path: .
  commands:
    install:
      status: false
    build:
      status: false
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
