version: '3'
services:
  analyzer-tiger:
    image: analyzer-tiger
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
    - ./:/go/src/github.com/reportportal/service-analyzer-equals/
    restart: on-failure
    ports:
    - 8080:8080